-- MySQL Script generated by MySQL Workbench
-- Wed Jan 13 17:56:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`table1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Disciplina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Disciplina` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Disciplina` (
  `idDisciplina` INT NOT NULL,
  `nombreDisciplina` VARCHAR(45) NULL,
  `descripcionDisciplina` VARCHAR(45) NULL,
  PRIMARY KEY (`idDisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Area Deportiva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Area Deportiva` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Area Deportiva` (
  `idCancha` INT NOT NULL,
  `nombreCancha` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `numeroDeCancha` INT NULL,
  `Etapa` VARCHAR(45) NOT NULL,
  `Disciplina_idDisciplina` INT NOT NULL,
  `Aforo` INT NULL,
  PRIMARY KEY (`idCancha`),
  UNIQUE INDEX `Descripcion_UNIQUE` (`Descripcion` ASC) VISIBLE,
  INDEX `fk_Cancha_Disciplina1_idx` (`Disciplina_idDisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_Cancha_Disciplina1`
    FOREIGN KEY (`Disciplina_idDisciplina`)
    REFERENCES `mydb`.`Disciplina` (`idDisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Persona` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Persona` (
  `idPersona` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(10) NULL,
  `telefono` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Responsable`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Responsable` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Responsable` (
  `idResponsable` INT NOT NULL,
  `Cargo` VARCHAR(45) NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idResponsable`),
  INDEX `fk_Responsable_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Responsable_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReservarCancha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ReservarCancha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ReservarCancha` (
  `idReserva` INT ZEROFILL NOT NULL,
  `horaInicioReserva` VARCHAR(45) NULL,
  `horaFinreserva` VARCHAR(45) NULL,
  `Cancha_idCancha` INT NOT NULL,
  `Responsable_idResponsable` INT NOT NULL,
  `fechaReserva` VARCHAR(45) NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_ReservarCancha_Cancha1_idx` (`Cancha_idCancha` ASC) VISIBLE,
  INDEX `fk_ReservarCancha_Responsable1_idx` (`Responsable_idResponsable` ASC) VISIBLE,
  CONSTRAINT `fk_ReservarCancha_Cancha1`
    FOREIGN KEY (`Cancha_idCancha`)
    REFERENCES `mydb`.`Area Deportiva` (`idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservarCancha_Responsable1`
    FOREIGN KEY (`Responsable_idResponsable`)
    REFERENCES `mydb`.`Responsable` (`idResponsable`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `numSocio` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `perfil` VARCHAR(45) NULL,
  `ReservarCancha_idReserva` INT ZEROFILL NOT NULL,
  `Persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_ReservarCancha1_idx` (`ReservarCancha_idReserva` ASC) VISIBLE,
  INDEX `fk_Usuario_Persona1_idx` (`Persona_idPersona` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_ReservarCancha1`
    FOREIGN KEY (`ReservarCancha_idReserva`)
    REFERENCES `mydb`.`ReservarCancha` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Persona1`
    FOREIGN KEY (`Persona_idPersona`)
    REFERENCES `mydb`.`Persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
